// <auto-generated />
using System;
using System.Collections.Generic;
using GeoRisk.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoRisk.API.Migrations.AddAllNewEntities
{
    [DbContext(typeof(GeoRiskDbContext))]
    [Migration("20260527195340_InitialAddAllNewEntities")]
    partial class InitialAddAllNewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.AiContextCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VectorHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("AiContextCaches");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.AiProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1024);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AiProviderConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MaxTokens = 1024,
                            Model = "deepseek-chat",
                            Provider = "DeepSeek",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApiKey = "",
                            BaseUrl = "http://localhost:11434/v1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MaxTokens = 1024,
                            Model = "qwen3:8b",
                            Provider = "Ollama",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ApiKey = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MaxTokens = 1024,
                            Model = "qwen-turbo",
                            Provider = "Qwen",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ApiKey = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MaxTokens = 1024,
                            Model = "claude-sonnet-4-20250514",
                            Provider = "Anthropic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ApiKey = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MaxTokens = 1024,
                            Model = "gpt-4o",
                            Provider = "OpenAI",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<double?>("AreaKm2")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EscalatedFromAlertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FwiValue")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid?>("GeoEventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<double?>("Temperature")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EscalatedFromAlertId");

                    b.HasIndex("GeoEventId");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Area")
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<double?>("AreaKm2Threshold")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int?>("ConsecutiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxFwi")
                        .HasColumnType("decimal(8,2)");

                    b.Property<double?>("MinFwi")
                        .HasColumnType("decimal(8,2)");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("decimal(8,2)");

                    b.Property<double?>("MinWindSpeed")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("NotifyRoles")
                        .HasColumnType("text[]");

                    b.Property<int?>("SeasonEndMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("SeasonStartMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("SeverityThreshold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveProvider = "DeepSeek",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.CitizenAlertSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision");

                    b.Property<int>("SeverityThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("Phone");

                    b.ToTable("CitizenAlertSubscriptions", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.DashboardCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DashboardCaches");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireHotspot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageFwi")
                        .HasColumnType("double precision");

                    b.Property<int>("AverageSeverity")
                        .HasColumnType("integer");

                    b.Property<Polygon>("CellGeometry")
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<string>("CommonWindDirection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("FireCount")
                        .HasColumnType("integer");

                    b.Property<string>("GridCellId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PeakHour")
                        .HasColumnType("integer");

                    b.Property<int>("PeakMonth")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<double>("TotalAreaBurned")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GridCellId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("RiskLevel");

                    b.ToTable("FireHotspots", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AffectedAreas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double?>("CauseConfidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationHours")
                        .HasColumnType("double precision");

                    b.Property<int?>("EvacuationCount")
                        .HasColumnType("integer");

                    b.Property<int?>("FirefightersDeployed")
                        .HasColumnType("integer");

                    b.Property<string>("FwiConditionsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneratedContent")
                        .HasColumnType("text");

                    b.Property<Guid>("GeoEventId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PeakFireAreaHa")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("PeakFireTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProbableCause")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StructuresDestroyed")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TimelineJson")
                        .HasColumnType("jsonb");

                    b.Property<double>("TotalAreaHa")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherConditionsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GeoEventId");

                    b.ToTable("FireReports");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireSpreadPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AffectedMunicipalities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FWI")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FireEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("HorizonHours")
                        .HasColumnType("integer");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("ISI")
                        .HasColumnType("double precision");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<double>("RosKmh")
                        .HasColumnType("double precision");

                    b.Property<int>("Scenario")
                        .HasColumnType("integer");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FireEventId");

                    b.HasIndex("Polygon");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Polygon"), "GIST");

                    b.HasIndex("FireEventId", "HorizonHours");

                    b.ToTable("FireSpreadPredictions", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Cim")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperationalZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Parish")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PersonnelCount")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("County");

                    b.HasIndex("District");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("Type");

                    b.ToTable("FireStations", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FwiForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BUI")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DC")
                        .HasColumnType("double precision");

                    b.Property<double>("DMC")
                        .HasColumnType("double precision");

                    b.Property<double>("FFMC")
                        .HasColumnType("double precision");

                    b.Property<double>("FWI")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GridPointId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer");

                    b.Property<double>("ISI")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDate");

                    b.HasIndex("GridPointId");

                    b.HasIndex("HorizonDays");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("ForecastDate", "HorizonDays");

                    b.ToTable("FwiForecasts", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.GeoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIClassification")
                        .HasColumnType("text");

                    b.Property<string>("AIInsight")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Severity");

                    b.ToTable("GeoEvents", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.HotspotAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FireHotspotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GeoEventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FireHotspotId");

                    b.HasIndex("GeoEventId");

                    b.HasIndex("IsRead");

                    b.ToTable("HotspotAlerts", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.NotificationQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitizenSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PushSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CitizenSubscriptionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PushSubscriptionId");

                    b.HasIndex("Status");

                    b.ToTable("NotificationQueueItems", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("PushSubscriptions", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.RiskZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("RiskZones", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.ScheduledReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Recipients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ScheduledReports");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.SeasonalStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageFwi")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageTemperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DailyFireCounts")
                        .HasColumnType("jsonb");

                    b.Property<string>("FireCauseBreakdown")
                        .HasColumnType("jsonb");

                    b.Property<double>("LargestFireHa")
                        .HasColumnType("double precision");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PeakFireDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalAreaHa")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalFires")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SeasonalStatistics");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.TerrainAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AspectDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("aspect_degrees");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<double>("ElevationMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_meters");

                    b.Property<string>("GridPointId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grid_point_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("NorthFacingPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("north_facing_percent");

                    b.Property<double>("SlopeDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("slope_degrees");

                    b.Property<double>("SolarExposureIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("solar_exposure_index");

                    b.Property<string>("TerrainComplexity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("terrain_complexity");

                    b.Property<string>("TerrainFireRiskContribution")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("terrain_fire_risk_contribution");

                    b.Property<double>("TerrainRiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("terrain_risk_score");

                    b.HasKey("Id");

                    b.HasIndex("GridPointId")
                        .HasDatabaseName("ix_terrain_analyses_grid_point_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_terrain_analyses_location");

                    b.ToTable("terrain_analyses", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.WeatherRiskDataPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BUI")
                        .HasColumnType("double precision");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<double>("DC")
                        .HasColumnType("double precision");

                    b.Property<double>("DMC")
                        .HasColumnType("double precision");

                    b.Property<double>("FFMC")
                        .HasColumnType("double precision");

                    b.Property<double>("FWI")
                        .HasColumnType("double precision");

                    b.Property<string>("GridPointId")
                        .HasColumnType("text");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("ISI")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<double>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GridPointId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Timestamp");

                    b.ToTable("WeatherRiskDataPoints", (string)null);
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.AiContextCache", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.GeoEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.Alert", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoRisk.API.Domain.Entities.Alert", "EscalatedFromAlert")
                        .WithMany()
                        .HasForeignKey("EscalatedFromAlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoRisk.API.Domain.Entities.GeoEvent", "GeoEvent")
                        .WithMany()
                        .HasForeignKey("GeoEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoRisk.API.Domain.Entities.User", null)
                        .WithMany("Alerts")
                        .HasForeignKey("UserId");

                    b.Navigation("AlertRule");

                    b.Navigation("EscalatedFromAlert");

                    b.Navigation("GeoEvent");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireReport", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.GeoEvent", "GeoEvent")
                        .WithMany()
                        .HasForeignKey("GeoEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoEvent");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireSpreadPrediction", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.GeoEvent", "FireEvent")
                        .WithMany()
                        .HasForeignKey("FireEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireEvent");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.HotspotAlert", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.FireHotspot", "FireHotspot")
                        .WithMany("Alerts")
                        .HasForeignKey("FireHotspotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoRisk.API.Domain.Entities.GeoEvent", "GeoEvent")
                        .WithMany()
                        .HasForeignKey("GeoEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FireHotspot");

                    b.Navigation("GeoEvent");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.NotificationQueueItem", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoRisk.API.Domain.Entities.CitizenAlertSubscription", "CitizenSubscription")
                        .WithMany()
                        .HasForeignKey("CitizenSubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoRisk.API.Domain.Entities.PushSubscription", "PushSubscription")
                        .WithMany()
                        .HasForeignKey("PushSubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alert");

                    b.Navigation("CitizenSubscription");

                    b.Navigation("PushSubscription");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GeoRisk.API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.FireHotspot", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("GeoRisk.API.Domain.Entities.User", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
